services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: passneedchange!
    ports:
      - "5432:5432"
    restart: always

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
    - start-dev
    - --db=dev-file
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data


volumes:
  keycloak-data:
    driver: local