spring.application.name=events

#========== PostgreSQL DB Configuration ==========
spring.datasource.url=jdbc:postgresql://dpg-d1jtjbumcj7s73abr660-a.frankfurt-postgres.render.com:5432/event_r0xw
spring.datasource.username=event_r0xw_user
spring.datasource.password=1ft2lqUJSepx863hKbzJbR3GGqprLcFb
#========== Hibernate / JPA ==========
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#========== Keycloak ==========
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/event-platform}
